### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by santigarcor** [elonmallin/vscode-phpunit#15]
First of all thank you for this package, it looks very promising. 

Currently i'm a ST3 user, and i use [a package](https://github.com/gerardroche/sublime-phpunit) for phpunit. It has great features like running the nearest test, running the whole file, all the tests or the last test ran. It also has a nice way of discovering the phpunit executable if you have the composer option enabled, so you don't have to make a specific configuration for each specific project. You could use some  features that the sublime text package has to improve or make this one more robust.

**Comment by elonmallin** [comment]
Hi, thanks for the feedback.

Yes, I like it. I've thought of some of these things but I'm only quite casually developing this extension so there is no timeline at the moment but I accept any contributions I can get. I don't use ST3 myself so I don't know which other feature this extension has except the ones you mentioned.

There is already kind of a nearest feature in there if the cursor is inside a functions scope it will put that at the top to choose from. So run the `phpunit.Test` command and press `down+enter` runs that test but it's true that you can't add a shortcut to it since you have to do `down+enter`.

I also like the idea of it just working out of the box, no config if phpunit is already installed with composer and possibly look in common directories for phpunit and just on the command line globally.

I'd say:
1. Add new command `phpunit.TestFunction` which will try and run the closest function. Then it can be bound to a keyboard shortcut too.

2. Find phpunit automatically in following order: composer, globally on command line and (common directories? (C:/xampp/php)). But keep the setting to allow manually setting the path.

If you feel like adding any of these features you're free to help. I'll keep this open to remember these tasks.

**Comment by santigarcor** [comment]
Ok, i could try to make that function thing but can't promise anything.

**Comment by santigarcor** [comment]
@elonmallin I figured a way to add colors to the output, if you want to try it check [this](https://github.com/santigarcor/vscode-phpunit/tree/output-colors) before i open the PR.

**Comment by elonmallin** [comment]
Checked it out. Looks really nice =) Can you add the colors based off of master and not the composer changes? I want to merge the colors into master and then rebase the composer branch off master.

**Comment by elonmallin** [comment]
I think we accomplished what this issue was originally for however it would still be nice with some color output. I noticed your branch is removed and there is also another extension out there that does colors so maybe I'll check out that one and add it. Did a release today though [v3.1.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v3.1.0) and the other points above were added already a long while ago.

Thanks for your help!
