### ISSUE TITLE
Path Mapping

### ISSUE THREAD

**Issue by danjohnson95** [elonmallin/vscode-phpunit#21]
I need to run my unit tests from a virtual machine. I managed to get this extension to use the vagrant installation of PHPUnit by setting the `phpunit.execPath` to the following:

    vagrant ssh -- /srv/api/vendor/bin/phpunit

but the path of the file I'm testing is relative to the host PC, and is not correct for my VM.

It would be great if I could specify path mapping.

**Comment by yurevichcv** [comment]
Same for Docker

**Comment by elonmallin** [comment]
I agree, that would be neat. I just finally started working some on the extension again. Have been a bit busy. But I want to create `drivers` like `"AbsolutePath", "Composer", "Phar", "GlobalPhpUnit", "Docker", "Ssh"`. And I have Docker and Ssh left to do (which are the trickier ones I guess). And I might try and do another release in between. Ppl seem to like colorized clickable output using `tasks` so that might come first.

I'll remember to write here again once I commit what I have to main so you're updated and free to help out and come with ideas.

Cheers

**Comment by yurevichcv** [comment]
Hi.

For now you can just replace absolute path to relative here:
```
if (putFsPathIntoArgs)
{
    args.push(vscode.window.activeTextEditor.document.uri.fsPath);
}
```
it will already help a lot.

**Comment by Nomad145** [comment]
Hi, @yurevichcv.

I'm new to VSCode.  Where should I place that condition in the editor configuration?

**Comment by elonmallin** [comment]
There is a new version out [v4.0.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v4.0.0). Check out the [readme](https://github.com/elonmallin/vscode-phpunit/blob/master/README.md) section about **Advanced config**.

Now you can use `phpunit.command` to set a custom command. And map paths with:
```json5
{
    "phpunit.paths": {
        "/local/path": "/virtual/path"
    }
}
```

Hope this fixes the issue.
