### ISSUE TITLE
extension does not run the command

### ISSUE THREAD

**Issue by JanuszOsica** [elonmallin/vscode-phpunit#24]
when i choose something from list, command is outputing but not running. 
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/17933890/41645409-3bf680b4-7471-11e8-8cdb-7ef80f2f0c2c.gif)

**Comment by elonmallin** [comment]
Hi, I think it's because of the path.
Maybe you could try setting it to `./vendor/bin/phpunit` otherwise absolute path should work. See the readme GIF example paths.

I have planned and prepared to make it find phpunit in the vendor folder automatically in a coming update. Just don't know when it's coming.

**Comment by JanuszOsica** [comment]
it also doesn't work for me

**Comment by elonmallin** [comment]
Realized the path on windows has to be an executable file. Check out this previously closed [issue](https://github.com/elonmallin/vscode-phpunit/issues/7) please. It describes how you can create a `.bat` file to execute. I think `BIN_TARGET` there should be the path you're running with now.

In the future however this will not be necessary as I mentioned, it will find the path automatically.

Hope that fixes it.
Cheers

**Comment by elonmallin** [comment]
This should now work in the latest release [v3.0.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v3.0.0) also published to the [marketplace](https://marketplace.visualstudio.com/items?itemName=emallin.phpunit). It will now find `php` if it exists globally and same for `phpunit` if it exists with composer in the vendor directories or as a .phar file. 

Please try again. I'll close this since the whole behavior changed and this should be working now.

**Comment by JanuszOsica** [comment]
now it's work. Thank you!
