### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by garygreen** [elonmallin/vscode-phpunit#26]
Not sure if this is a vscode issue or not, but when you enable colours with `--colors=always` phpunit option, there is no colours displayed in the vscode window - is this because it's being output to the debug console view rather than run in a terminal window?

![image](https://user-images.githubusercontent.com/1702638/46427972-ac724280-c73a-11e8-8c82-aa3290f93276.png)

**Comment by elonmallin** [comment]
I think its a vscode issue. Im not doing anything special except spawning a console and running the commands so if there are no colors the problem I assume is with the console.

You could try running the command manually in a vscode console and see if it even works there. Also make sure the parameters you expect are shown when you run the extension normally.

It should be possible to get colored output since I've seen other extensions have it but I'm not sure when I'll look into that yet.

**Comment by walkero-gr** [comment]
That would be great thing to have. 
@elonmallin If you check @garygreen screenshot, you will notice that the terminal colour codes are printed at the terminal. My guess is that are not parsed right by VSCode terminal. Maybe there is an other way to print at the terminal, having the colours working. I know that Better PHPUnit does that.

I had a fast check at it's code and it uses the vscode.ShellExecution function (https://code.visualstudio.com/api/references/vscode-api#ShellExecution) instead the OutputChannel you use. I am not sure if this is exactly the way to do it and how much work does it actually need. I am trying to help.

**Comment by bedus-creation** [comment]
yes No colors. Please Do It otherwise I will moved to another one.

**Comment by elonmallin** [comment]
Released a new update that has color output and will show failed tests in problems pane. Some docker support is added too [v4.0.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v4.0.0). This should take care of the issue, cheers.
