### ISSUE TITLE
Not working, no error

### ISSUE THREAD

**Issue by hiboudev** [elonmallin/vscode-phpunit#27]
Hi,

I installed PHPUnit, added this to my config file :
```
    "phpunit.php": "E:\\easyPhp\\eds-binaries\\php\\php713vc14x86x181021165540\\php.exe",
    "phpunit.phpunit": "E:\\dev\\third-party-libs\\PHPUnit\\phpunit-7.4.3.phar",
    "phpunit.args": [
        "--configuration",
        "./phpunit.xml.dist"
    ]
```

I created a test class :
```
<?php

namespace wcf\data\siraca\participation;

// use PHPUnit\Framework\TestCase;

class ParticipationOrganizerTest extends \PHPUnit_Framework_TestCase
{
    public function testTest()
    {
        $this->assertTrue(true);
    }
}
```

I select the method, CTRL+SHIFT+P, execute command PHPUnit Test... and nothing happens, no error, no console output...

Did I miss something ?

**Comment by elonmallin** [comment]
There is a new release out today [v3.1.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v3.1.0) where I updated the dependencies to vscode and typescript. Maybe that helps.

As to the original issue it looks all right. Did you try different slashes? `/` or just one `\`. As a side note, if you put the phar file in your workspace directory it should be found automatically.

Hope that helps =) Otherwise could you please provide some logging output?

**Comment by elonmallin** [comment]
I'll close this as there is yet another version out [v4.0.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v4.0.0).
