### ISSUE TITLE
phpunit.args with docker commands

### ISSUE THREAD

**Issue by gayanhewa** [elonmallin/vscode-phpunit#44]
Hi @elonmallin I can't seem to get the phpunit config to get loaded when running the tests via docker-compose commands. Is there any workaround. It seems to ignore my values from phpunit.args

**Comment by elonmallin** [comment]
Hi, could you check the **OUTPUT** and **TERMINAL -> Task for phpunit** panes what command you're running, maybe paste them here? There you'll see the full command that's being run and maybe notice some problem with some path.

I guess your settings is something like:
```json
{
    "phpunit.args": ["-c", "./phpunit.xml"],
    "phpunit.command": "docker-compose run --rm service_name",
    "phpunit.paths": {
        "${workspaceFolder}": "/app"                // Map your ${workspaceFolder} to where it
    }
}
```

One gotcha here would be that `./phpunit.xml` is relative to the current directory. Which depends on what the default directory is in your container I think. Try specifying the full path to make sure we find the file and use the `phpunit.paths` to map it correctly in your container =)

As a side note I'll recommend the [Demote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension.

**Comment by gayanhewa** [comment]
The output doesn't seem to show the phpunit.xml path at all for me 🤔 

```
> Executing task: docker-compose run --rm test__shell '/opt/project/vendor/bin/phpunit' --colors=always '/opt/project/tests/PaymentControllerTest.php' <
```

My settings has:

```
    "phpunit.args": [
        "-c",
        "/opt/project/tests/phpunit.xml"
    ],
    "phpunit.paths": {
        "${workspaceFolder}": "/opt/project"
    },
```

I will also look into the remote development extension.

**Comment by elonmallin** [comment]
Hmm yea that's strange, `phpunit.xml` should be there. You don't happen to have another setting in your workspace or something that is overriding this one? There should at least be one setting missing from what you sent I guess:
```
  "phpunit.command": "docker-compose run --rm test__shell"
```

Possible workaround could be to manually put the `phpunit.xml` in your current working directory in your container since it should get picked up automatically then [as seen in the docs](https://phpunit.readthedocs.io/en/9.1/organizing-tests.html#composing-a-test-suite-using-xml-configuration).

Could you also have a look at the *OUTPUT* pane, should be the second one from the left down where the terminal is and will have very similar output to the *TERMINAL -> Task* pane that you pasted =)

**Comment by gayanhewa** [comment]
🤦 my bad. I had a local settings.json that had overridden `phpunit.args` with a empty block.

**Comment by gayanhewa** [comment]
Thanks for your time @elonmallin 🙇
