### ISSUE TITLE
No output from PHPUnit

### ISSUE THREAD

**Issue by YMIndustries** [elonmallin/vscode-phpunit#7]
Hi,

I'm trying to use this for my CakePHP project.

My config looks like this:

    {
        "phpunit.execPath": "C:\\wamp\\bin\\php\\php5.5.12\\php.exe vendor\\phpunit\\phpunit\\phpunit",
        "phpunit.args": []
    }

When I try to run a test, the output panel in VSCode has the following added to it:

>C:\wamp\bin\php\php5.5.12\php.exe vendor\phpunit\phpunit\phpunit --filter testCannotViewCircleWithEmptyUserId ./tests/TestCase/Controller/CalendarControllerTest.php

Then nothing further is outputted. If I open Command Prompt in my project directory and run the same command my tests run.

I've seen the other similar issues and tried what they suggested but still have this issue. (I restarted VSCode without any change, and I can't use phpunit.bat because that applies to the PHPUnit supplied with xampp, but not the one supplied with CakePHP.

Help would be greatly appreciated, thanks!

**Comment by elonmallin** [comment]
Hi,

The config variable `phpunit.execPath` has to be an executable file with no arguments.

But you could probably create your own phpunit.bat file and execute that. This is the one I use:
```
@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../phpunit/phpunit/phpunit
php "%BIN_TARGET%" %*
```
You just have to make sure php is accessible from the command line like that otherwise provide the full path. And BIN_TARGET should point to phpunit in your vendor folder.

Another option I assume could be something like:
```
{
    "phpunit.execPath": "C:\\wamp\\bin\\php\\php5.5.12\\php.exe",
    "phpunit.args": [".\\vendor\\phpunit\\phpunit\\phpunit"]
}
```
This would be kind of hacking the whole system but should also work (I haven't tried it).

Let me know if that helps. Sorry I couldn't get around to answering sooner.

Cheers

**Comment by YMIndustries** [comment]
It works! Thanks so much for that, this extension will make my life just that little bit easier.

**Comment by elonmallin** [comment]
Okey, great!
